language: node_js
node_js:
  - "5.5"
  - "4.2"
  - "0.10"
git:
  depth: 10
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
    - npm install
    - npm test
